### PR TITLE
Blocking reporting

### LINKED ISSUE #25: User Blocking & Reporting

### PR DESCRIPTION
**Pull request by aditidagar**
Implemented user blocking feature. Use /blockUser route with to allow srcUser to block TargetUser.

Fixes #25 

Co-authored by @Lakshya2610

### CODE REVIEW

**Comment by gautamgireesh** [comment]
image
I think there is something wrong with the backend file. Check it and confirm

**Comment by Lakshya2610** [comment]
> image
> I think there is something wrong with the backend file. Check it and confirm

add this line to top of the file in Chat.js 
const DB = require("./DatabaseManager");

**Comment by gautamgireesh** [comment]
> > image
> > I think there is something wrong with the backend file. Check it and confirm
> 
> add this line to top of the file in Chat.js
> const DB = require("./DatabaseManager");

image
That didn;t fix it, the same error pops up when I try running the backend.

**Comment by Lakshya2610** [comment]
@gautamgireesh It should be fine now

**Pull request merged**
