### PR TITLE
implemented chunk loading for connections

### LINKED ISSUE #62: Implement Chunk Loading of Potential Connections
Currently, the server replies with all of the potential connections. Ideally, it should reply with a set of 'x' connections at a time, with more sets upon successive requests

### PR DESCRIPTION
**Pull request by aditidagar**
Implemented chunk loading for potential connections. Chunk size is set to 25.
Fixes #62 
Co-authored by @Lakshya2610

### CODE REVIEW

**Comment by Lakshya2610** [comment]
We need to optimize database call throughout the server. We'll just do that in this branch. That's why we're adding Needs work tag for now

**Comment by gautamgireesh** [comment]
image

**Comment by Lakshya2610** [comment]
@gautamgireesh This is fine now. I merged master into branch, so it automatically ran unit tests and passed all of them. You can look at the test results [here](https://github.com/Lakshya2610/Findr/pull/64/checks?check_run_id=880184854)

**Comment by gautamgireesh** [comment]
@Lakshya2610 I get the same error even now, after git pull.

**Pull request merged**
